# Site settings
title: "Sherlocke: Powered by IBM Watson"
description: A smarter research tool for the modern age.
url: "http://sherlocke.me"
email: contact@unhaltable.com
twitter_username: sherlockeapp
github_username:  sherlocke

# Build settings
exclude: ['README.md']
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Site nav
navigation:
 - title: Product
   url:   /product/
 - title: Pricing
   url:   /pricing/
 - title: Dev Blog
   url:   /blog/
