# Site settings
title: "Sherlocke: Powered by IBM Watson"
email: your-email@domain.com
description: With the power of IBM Watson, Sherlocke enhances CanLII.
url: "http://sherlocke.me"
twitter_username: unhaltable
github_username:  sherlocke

# Build settings
exclude: ['README.md']
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: :compressed
