# Site settings
title: "Sherlocke: Powered by IBM Watson"
email: contact@unhaltable.com
description: With the power of IBM Watson, Sherlocke enhances CanLII.
url: "http://sherlocke.me"
twitter_username: sherlockeapp
github_username:  sherlocke

# Build settings
exclude: ['README.md']
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: :compressed

# Site nav
navigation:
 - title: Product
   url: /product/
 - title: Dev Blog
   url: /blog/
